name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release for (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag || github.ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: true

      - name: Get tag name
        id: get_tag
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
            echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
            echo "Using manually specified tag: ${{ inputs.tag }}"
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "Using pushed tag: ${GITHUB_REF#refs/tags/}"
          fi

      - name: Build for Linux amd64
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o stashdir-linux-amd64 ./cmd/stashdir

      - name: Build for Linux arm64
        run: |
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o stashdir-linux-arm64 ./cmd/stashdir

      - name: Build for macOS amd64
        run: |
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o stashdir-darwin-amd64 ./cmd/stashdir

      - name: Build for macOS arm64
        run: |
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o stashdir-darwin-arm64 ./cmd/stashdir

      - name: Build for Windows amd64
        run: |
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o stashdir-windows-amd64.exe ./cmd/stashdir

      - name: Build for Windows arm64
        run: |
          GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o stashdir-windows-arm64.exe ./cmd/stashdir

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: |
            stashdir-linux-amd64
            stashdir-linux-arm64
            stashdir-darwin-amd64
            stashdir-darwin-arm64
            stashdir-windows-amd64.exe
            stashdir-windows-arm64.exe
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}